package utils;

public enum Blocks {
    MAZE_BOUNDS,
    GHOST_CAGE,
    HOR_ONE_ROW_BLOCK,
    VER_ONE_ROW_BLOCK,
    HOR_TWO_ROW_BLOCK,
    VER_TWO_ROW_BLOCK,
    HOR_THREE_ROW_BLOCK,
    VER_THREE_ROW_BLOCK,
    RIGHT_HOR_T_SHAPED_BLOCK,
    LEFT_HOR_T_SHAPED_BLOCK,
    UP_VER_T_SHAPED_BLOCK,
    DOWN_VER_T_SHAPED_BLOCK,
    L_SHAPED_BLOCK,
    CROSS_BLOCK
}
